### PR TITLE
Add Manifest IDs for sensors used by LTMHM.

### PR DESCRIPTION
**Pull request by tgipsonMIDE**

### CODE REVIEW

**Comment by StokesMIDE** [comment]
Should the new entries have `<SensorConfig>` child elements? IMHO, all sensors probably should, as a bit of future-proofing. It doesn't affect anything if the element isn't actually included.

**Comment by StokesMIDE** [comment]
> Probably not the place for this discussion, but the main purpose I could see for these sensors is to specify the bus# the sensor is attached to - which really should be a standard element IMO rather than sensor-specific (at the risk of gradually reinventing DeviceTree).

Yeah, really not the place for this discussion 😛 . Especially since we've already shipped hundreds of devices using SensorConfig elements.

As you've argued in the past, the manifest is internal plumbing the user should generally never see, so magic numbers aren't quite so bad. What the SensorConfig values do is entirely up to things in the firmware. Presumably, whoever is constructing a manifest (i.e., is creating new hardware) has access to the source.

> Any reason to add "just in case" SensorConfig elements upfront vs. at time of first use (for a given sensor)?

Adding it to the schema now means we don't have to update the schema in the future if we decide we need additional sensor configuration data. Our parsers are a bit lax and can deal with it, but child elements not explicitly defined in the schema are technically invalid.

This is largely academic, though. I'm fine approving the change without adding the child elements to the schema.

**Review by StokesMIDE — APPROVED** [review]
Adding `<SensorConfig>` elements might be good for future use, but not mandatory.

**Comment by tgipsonMIDE** [comment]
Thanks!

**Pull request merged**
